### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by imaffett** [Wizcorp/cordova-plugin-gamecenter#19]
With Cordova switching to NPM for their registry, could you publish this plugin there?

https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by jrouault** [comment]
Thanks for the reminder! It will be done asap.

**Comment by jrouault** [comment]
Now available on NPM:
https://www.npmjs.com/package/cordova-plugin-gamecenter
